/**
 * PR creation via the `gh` CLI.
 *
 * Pushes the feature branch and opens the PR. Any push failure is surfaced
 * as a thrown error (with the real git stderr) so the caller can handle it
 * via the pr_creation_blocked path without discarding the dev work.
 */

import { $ } from "bun";
import { config } from "@/config";
import { logger } from "@/utils/logger";
import type { Issue, PrStatus } from "@/types/pipeline";

const log = logger.child({ component: "github_pr" });

export interface CreatePrResult {
  prUrl: string;
  prNumber: number;
  prStatus: PrStatus;
}

export interface CreatePrInput {
  issue: Issue;
  branch: string;
  worktreePath: string;
  reviewCycles: number;
  flagged: boolean;
  unresolvedFeedback: string | null;
}

export async function createPr(input: CreatePrInput): Promise<CreatePrResult> {
  const cfg = config();
  const { issue, branch, worktreePath, reviewCycles, flagged, unresolvedFeedback } = input;

  // Push the feature branch. If the remote branch already exists from a
  // previous attempt, fall back to a plain push without --set-upstream.
  try {
    await $`git -C ${worktreePath} push --set-upstream origin ${branch}`.quiet();
  } catch (err) {
    const stderr = readShellStderr(err);
    const exitCode = readShellExitCode(err);

    if (/already exists/.test(stderr)) {
      await $`git -C ${worktreePath} push origin ${branch}`.quiet();
    } else {
      throw new Error(
        `git push failed (exit ${exitCode}): ${stderr.slice(0, 1000) || "(no stderr)"}`,
      );
    }
  }

  // Open the PR via `gh`.
  const title = formatPrTitle(issue, flagged);
  const body = renderPrBody({ issue, reviewCycles, flagged, unresolvedFeedback });
  let prOutput: string;
  try {
    prOutput = await $`gh pr create \
      --title ${title} \
      --body ${body} \
      --head ${branch} \
      --base ${cfg.gitDefaultBranch} \
      --repo ${slugFromUrl(cfg.repoUrl)}`
      .cwd(worktreePath)
      .text();
  } catch (err) {
    const stderr = readShellStderr(err);
    const exitCode = readShellExitCode(err);
    throw new Error(
      `gh pr create failed (exit ${exitCode}): ${stderr.slice(0, 1000) || "(no stderr)"}`,
    );
  }

  const prUrl = prOutput.trim().split("\n").pop()!.trim();
  const prNumber = extractPrNumber(prUrl);
  const prStatus: PrStatus = flagged ? "flagged" : "ready";

  log.info("pr created", { issueId: issue.id, prUrl, prNumber, prStatus });
  return { prUrl, prNumber, prStatus };
}

function formatPrTitle(issue: Issue, flagged: boolean): string {
  const clean = issue.title.replace(new RegExp(`^${escapeRegex(issue.id)}:\\s*`), "");
  const base = `${issue.id}: ${clean}`;
  return flagged ? `${base} [NEEDS ATTENTION]` : base;
}

function renderPrBody(opts: {
  issue: Issue;
  reviewCycles: number;
  flagged: boolean;
  unresolvedFeedback: string | null;
}): string {
  const { issue, reviewCycles, flagged, unresolvedFeedback } = opts;
  const lines: string[] = [];

  if (flagged) {
    lines.push("> **NEEDS ATTENTION** — review cycles exhausted. Unresolved items below.", "");
  }

  lines.push(
    "## Linear",
    `- Issue: **${issue.id}** — ${issue.title.replace(new RegExp(`^${escapeRegex(issue.id)}:\\s*`), "")}`,
    "",
    "## Implementation notes",
    "",
    "Generated by the AI Dev Orchestrator. The branch was produced by a Claude Code agent in an isolated worktree and passed through the reviewer loop.",
    "",
    `- Review cycles: **${reviewCycles}**`,
    `- Status: **${flagged ? "flagged" : "ready"}**`,
  );

  if (unresolvedFeedback) {
    lines.push("", "## Unresolved reviewer feedback", "", unresolvedFeedback);
  }

  lines.push("", "## Ticket requirements", "", issue.description);

  return lines.join("\n");
}

export interface MergePrInput {
  prNumber: number;
  worktreePath: string;
  strategy: "squash" | "merge" | "rebase";
  repoUrl: string;
}

/**
 * Merge an open PR via `gh pr merge`. Called by the pipeline when AUTO_MERGE
 * is enabled and the reviewer returned a clean pass.
 *
 * Uses `--admin` to bypass any required-review protections (the AI reviewer
 * is the quality gate; we don't need a second human approval).
 * Throws on failure so the caller can fall back gracefully.
 */
export async function mergePr(input: MergePrInput): Promise<void> {
  const { prNumber, worktreePath, strategy, repoUrl } = input;
  const strategyFlag = `--${strategy}`;
  try {
    await $`gh pr merge ${prNumber} ${strategyFlag} --admin --repo ${slugFromUrl(repoUrl)}`
      .cwd(worktreePath)
      .quiet();
  } catch (err) {
    const stderr = readShellStderr(err);
    const exitCode = readShellExitCode(err);
    throw new Error(
      `gh pr merge failed (exit ${exitCode}): ${stderr.slice(0, 1000) || "(no stderr)"}`,
    );
  }
  log.info("pr auto-merged", { prNumber, strategy });
}

function extractPrNumber(prUrl: string): number {
  const match = prUrl.match(/\/pull\/(\d+)/);
  if (!match) throw new Error(`Could not parse PR number from: ${prUrl}`);
  return Number.parseInt(match[1], 10);
}

function slugFromUrl(repoUrl: string): string {
  const match = repoUrl.match(/github\.com[/:]([^/]+)\/([^/]+?)(?:\.git)?$/);
  if (!match) throw new Error(`Cannot parse GitHub slug from REPO_URL: ${repoUrl}`);
  return `${match[1]}/${match[2]}`;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Extracts stderr from a Bun ShellError (or any thrown value).
 * Returns "" if unreachable.
 */
function readShellStderr(err: unknown): string {
  if (!err || typeof err !== "object") return "";
  const buf = (err as { stderr?: unknown }).stderr;
  if (buf === undefined || buf === null) return "";
  if (typeof buf === "string") return buf;
  if (buf instanceof Uint8Array) return new TextDecoder().decode(buf);
  if (typeof (buf as { toString?: unknown }).toString === "function") return String(buf);
  return "";
}

function readShellExitCode(err: unknown): number | string {
  if (err && typeof err === "object" && "exitCode" in err) {
    const code = (err as { exitCode: unknown }).exitCode;
    if (typeof code === "number") return code;
  }
  return "?";
}
